spring:
  redis:
    host: redis.ms-orders.internal
    port: 6379
    timeout: 2000
    password: ${REDIS_PASSWORD}  # opcional según tu estándar
    redisson:
      connectionMinimumIdleSize: Nuevo
      connectionPoolSize: 100
      idleConnectionTimeout: 10000
      pingTimeout: 1000
      config: c
      address: redis://redis.ms-orders.internal:6379
      timeout: 2000